---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mautic-hpa
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mautic
  metrics:
    -
      type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
