apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mautic-issuer
spec:
  acme:
    email: skippednote@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: mautic-private
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
